---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-operator
  name: istio-test-ingressgateway
spec:
  profile: empty
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: "istio-test"
        enabled: true
        k8s:
          service:
            type: ClusterIP
        label:
          istio: istio-ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false

